import {
  HomeIcon,
  StarIcon,
  RocketIcon,
  TrophyIcon,
  CrownIcon,
  PromotionsIcon,
  OriginalsIcon,
  SlotsIcon,
  LiveCasinoIcon,
  BlackjackIcon,
  RouletteIcon,
  GameShowsIcon,
  ProvidersIcon,
} from "@/components/icons";

export const navItems = [
  { label: "Home", icon: HomeIcon, href: "/" },
  { label: "Favourites", icon: StarIcon, href: "/favourites" },
  { label: "Latest Releases", icon: RocketIcon, href: "/latest" },
  {
    label: "Challenges",
    icon: TrophyIcon,
    href: "/challenges",
  },
  {
    label: "Promotions",
    icon: PromotionsIcon,
    href: "#",
    children: [
      { label: "100K Weekly Race", badge: "4d" },
      { label: "$88,888 Baccarat R...", badge: "4d" },
      { label: "$2M Pragmatic D...", badge: "4d" },
    ],
  },
  { label: "Originals", icon: OriginalsIcon, href: "/originals" },
  { label: "Slots", icon: SlotsIcon, href: "/slots" },
  { label: "Live Casino", icon: LiveCasinoIcon, href: "/live-casino" },
  { label: "Blackjack", icon: BlackjackIcon, href: "/blackjack" },
  { label: "Roulette", icon: RouletteIcon, href: "/roulette" },
  { label: "Game Shows", icon: GameShowsIcon, href: "/game-shows" },
  { label: "Providers", icon: ProvidersIcon, href: "/providers" },
  { label: "VIP", icon: CrownIcon, href: "/vip" },
  // { label: "Blog", icon: BlogIcon, href: "/blog" },
  // { label: "Affiliate", icon: AffiliateIcon, href: "/affiliate" },
  // { label: "Live Support", icon: SupportIcon, href: "/support" },
];
